version: '3.8'

services:
  web:
    build: .
    container_name: moneyhub_app
    ports:
      - "5005:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
